[build]
  command = "hugo --gc --minify --cleanDestinationDir"
  publish = "public"
  
[context.production.environment]
  HUGO_VERSION = "0.139.0"  # 替换为你的Hugo版本
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  
[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL --verbose --verboseLog"
  
[context.branch-deploy]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL --verbose --verboseLog"
